[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cortex-agent-runtime"
version = "0.1.0"
description = "A runtime generic for executing agents with a Snowflake control plane"
dependencies = [
    "snowflake-snowpark-python",
    "pydantic",
    "pyyaml"
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "mkdocs-material"
]

[project.scripts]
cortex = "cortex_runtime.cli:main"
